version: 2
exclude_patterns:
- "**/*.spec.ts"
checks:
  similar-code:
    config:
      threshold: 90
  file-lines:
    config:
      threshold: 1000
  method-lines:
    config:
      threshold: 200
  complex-logic:
    config:
      threshold: 15
  identical-code:
    config:
      threshold: 96