title: DCK Project documentation
logo: ./logo-small.png
description: ""
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
#github: [metadata]
repository: agilevisioncompany/dck
gems:
  - 'jekyll-github-metadata'
